### ISSUE TITLE
Unable to install on Linux

### ISSUE THREAD

**Issue by msolefonte** [jolzee/chat-teneo-vue#1]
**Describe the bug**
When I try to run `npm install` I get some warnings related to the OS (It seems like it is expecting Mac OS), and optional packages are not installed. After that, I get some errors that audit can not fix and can not serve neither because of ESLint. I do not know if it is related of if there are three independent problems.

**To Reproduce**
1. Clone the project from GitHub on a LInux Desktop
2. Go to the project folder
3. Run `npm install`

**Expected behavior**
I expect the project to be installed.

**Logs**
**npm install**
```bash
> grpc@1.19.0 install /home/msole/Documents/code/tfg/chat-teneo-vue/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
[grpc] Success: "/home/msole/Documents/code/tfg/chat-teneo-vue/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote

> yorkie@2.0.0 install /home/msole/Documents/code/tfg/chat-teneo-vue/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1963 packages from 1722 contributors and audited 36899 packages in 39.615s
found 12 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```
**npm audit fix**
```bash
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 9.464s
fixed 0 of 12 vulnerabilities in 36899 scanned packages
  12 vulnerabilities required manual review and could not be updated
```
**npm run serve**
```bash
> chat-teneo-vue-new@0.1.0 serve /home/msole/Documents/code/tfg/ptolomeo-frontend
> vue-cli-service serve --open

 INFO  Starting development server...
 98% after emitting CopyPlugin                                                 

 ERROR  Failed to compile with 1 errors                                                                     12:02:06

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint/lib/config.js:342:29)
    at processText (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint-loader/index.js:263:17)
    at transform (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/eslint-loader/index.js:237:18)
    at /home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/loader-fs-cache/index.js:127:18
    at ReadFileContext.callback (/home/msole/Documents/code/tfg/ptolomeo-frontend/node_modules/loader-fs-cache/index.js:31:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

```
**Desktop (please complete the following information):**
 - OS: Kubuntu 17.10 64-bit
 - NPM Version: 6.4.1
 - Project Version: 0.1.0

**Comment by jolzee** [comment]
Haven't noticed that particular error before in any of my linux based docker containers. I did check in an update 3adf09da8b80292ee418760160427b3c1dba8885 recently which hopefully helps webpack find the eslint config in your case.

**Comment by msolefonte** [comment]
I generated an eslint config file and it just worked, but audit errors are still there. Perhaps it has something to do with my machine.

**Comment by msolefonte** [comment]
Solved with the eslint patch.
