### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by HINW** [jolzee/chat-teneo-vue#7]
Hi guys,

Any help with this? It always crash on load_balancer_api.o. 
I run om Arch Linux

 {
  'leopard-chat-teneo-vue': '0.1.0',
  npm: '6.10.2',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.39.2',
  node: '12.9.1',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.31.0',
  v8: '7.6.303.29-node.15',
  zlib: '1.2.11'
}

Here the output from the terminal.

Thank you in advance.

Cheers!

```
CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.o
../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc: In function ‘grpc_grpclb_request* grpc_grpclb_request_create(const char*)’:
../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:70:10: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 128 equals destination size [-Werror=stringop-truncation]
   70 |   strncpy(req->initial_request.name, lb_service_name,
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   71 |           GRPC_GRPCLB_SERVICE_NAME_MAX_LENGTH);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:492: Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.o] Error 1
make: Leaving directory '/home/hinw/Dev/projects/leopard/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hinw/Dev/projects/leopard/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.11-arch1-1-ARCH
gyp ERR! command "/home/hinw/.nvm/versions/node/v12.9.1/bin/node" "/home/hinw/Dev/projects/leopard/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/hinw/Dev/projects/leopard/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/hinw/Dev/projects/leopard/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/hinw/Dev/projects/leopard/node_modules/grpc
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/hinw/.nvm/versions/node/v12.9.1/bin/node /home/hinw/Dev/projects/leopard/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/hinw/Dev/projects/leopard/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/hinw/Dev/projects/leopard/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/hinw/Dev/projects/leopard/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.2.11-arch1-1-ARCH
node-pre-gyp ERR! command "/home/hinw/.nvm/versions/node/v12.9.1/bin/node" "/home/hinw/Dev/projects/leopard/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/hinw/Dev/projects/leopard/node_modules/grpc
node-pre-gyp ERR! node -v v12.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/hinw/.nvm/versions/node/v12.9.1/bin/node /home/hinw/Dev/projects/leopard/node_modules/node-gyp/bin/node-gyp.js build --fallback-to``
```

**Comment by jolzee** [comment]
Is the same problem there if you use Node v10.16.2?

**Comment by HINW** [comment]
Not sure. Let me try and check this out.

I'll report back later.

Cheers,
Henrik

⁣Få BlueMail for Android ​

5. sep. 2019, 02:40 kl. 02:40 skrev Peter Joles <notifications@github.com>:

**Comment by HINW** [comment]
Hi,

v10.16.2 did the magic. Thanks!
